apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 8080
---

apiVersion: v1
kind: Pod
metadata:
  name: animals
spec:
  containers:
  - name: animals
    image: supergiantkir/animals:bear
    ports:
    - containerPort: 80
