apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: demo-pod-1
spec:
 containers: 
 - name: nginx 
   image: nginx:1.7.9 
   volumeMounts:
   - name: my-volume
     mountPath: /cache
   ports: 
   - containerPort: 80
 - name: spring
   image: yanivomc/spring-music:latest
   volumeMounts:
   - name: my-volume
     mountPath: /cache
   ports:
   - containerPort: 8080
 volumes:
 - name: my-volume
   hostPath:
    path: /cache
    type: DirectoryOrCreate
